sudo: required
services:
    - docker

before_install:
    - docker build -t dvillaj/react-test -f ./client/Dockerfile.dev ./client

script:
    # To Make sure that the tests exits we use the --coverage param
    - docker run dvillaj/react-test npm test -- --coverage

after_success:
    - docker build -t dvillaj/multi-client ./client
    - docker build -t dvillaj/multi-nginx ./nginx
    - docker build -t dvillaj/multi-server ./server
    - docker build -t dvillaj/multi-worker ./worker
